[build]
    command = "npm install"
    functions = './translate/'

[functions]
    directory = "translate"

[[redirects]]
    from = "/translate"
    to = ".netlify/translate"
    status = 200
    force = true