[build]
    command = "npm install"
    functions = './functions/'

[[redirects]]
    from = "/translate"
    to = ".netlify/functions/translate"
    status = 200
    force = true

[[redirects]]
    from = "/passthru"
    to = ".netlify/functions/passthru"
    status = 200
    force = true
